name: 'HelloWorldActionGabrielGn'
description: 'Wait a designated number of milliseconds'
inputs:
  filepath:
    description: 'package.json path'
    required: false
    default: './package.json'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
