name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gabriel-gn/hello-world-github-action@v0.0.3
        with:
          milliseconds: 1000
