name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  check-version:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v2
        id: checkout
        with:
          path: "hello-world-github-action"
      - name: Check package.json
        needs: checkout
        id: check
        uses: ./
        with:
          filepath: 'hello-world-github-action/package.json'
